### ISSUE TITLE
processed_data download address is not valid. 

### ISSUE THREAD

**Issue by Zhangzhixiang-laugh** [ito-takuya/multitaskrepresentations#1]
”processed_data/: contains processed (or derivative) data required to generate figure panels in the Jupyter Notebooks. Data can be accessed [here](https://drive.google.com/drive/folders/1juQrDbHnNIiz7V6J-GqM4GCta9YiwVNV?usp=sharing).“
The address is not valid, can you update the latest address? Thanks!

**Comment by ito-takuya** [comment]
apologies! the link has been updated: https://drive.google.com/drive/folders/1ooZgxGzVtkgHmeZz7BZI79qcYML2XFwX?usp=sharing
